CREATE EXCEPTION EXC_REGISTRO_EXISTENTE 'REGISTRO JÁ CADASTRADO';

CREATE EXCEPTION EXC_REGISTRO_INEXISTENTE 'REGISTRO NÃO ENCONTRADO';

CREATE EXCEPTION EXC_CODIGO_NULO 'VALOR NULO PARA O CÓDIGO, PROCESSO ABORTADO!';