-- TABELA TIPO_PESSOA -------------------------------
CREATE TABLE TB_TIPOPESSOA (
  CODIGO INTEGER NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL  
)

ALTER TABLE TB_TIPOPESSOA  ADD PRIMARY KEY(CODIGO);

CREATE GENERATOR GEN_TIPOPESSOA;
SET GENERATOR GEN_TIPOPESSOA TO 0;

CREATE TRIGGER TR_TIPOPESSOA FOR TB_TIPOPESSOA BEFORE INSERT
AS
BEGIN
    new.CODIGO = GEN_ID(GEN_TIPOPESSOA, 1);
END

-- TABELA PESSOA -------------------------------
CREATE TABLE TB_PESSOA (
  CODIGO INTEGER NOT NULL,
  COD_TIPOPESSOA INTEGER NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  RG VARCHAR(20),  
  CPF VARCHAR(12),
  CNPJ VARCHAR(25),
  DT_NASC VARCHAR(12),
  EMAIL VARCHAR(100),
  FONE VARCHAR(20),
  CEP VARCHAR(9) NOT NULL,
  LOGRADOURO VARCHAR(100) NOT NULL,
  NUMERO INTEGER,
  BAIRRO VARCHAR(80) NOT NULL,
  CIDADE VARCHAR(80) NOT NULL,
  ESTADO VARCHAR(80) NOT NULL,
  PAIS VARCHAR(50),  
  COMPLEMENTO VARCHAR(100),
  PRIMARY KEY(CODIGO)  
)

ALTER TABLE TB_PESSOA  ADD PRIMARY KEY(CODIGO);
ALTER TABLE TB_PESSOA ADD FOREIGN KEY(COD_TIPOPESSOA) REFERENCES TB_TIPOPESSOA (CODIGO);

CREATE GENERATOR GEN_PESSOA;
SET GENERATOR GEN_PESSOA TO 0;

CREATE TRIGGER TR_PESSOA FOR TB_PESSOA BEFORE INSERT
AS
BEGIN
    new.CODIGO = GEN_ID(GEN_PESSOA, 1);
END


-- TABELA TIPO_PRODUTO -------------------------------
CREATE TABLE TB_TIPOPRODUTO (
  CODIGO INTEGER NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL  
)

ALTER TABLE TB_TIPOPRODUTO  ADD PRIMARY KEY(CODIGO);

CREATE GENERATOR GEN_TIPOPRODUTO;
SET GENERATOR GEN_TIPOPRODUTO TO 0;

CREATE TRIGGER TR_TIPOPRODUTO FOR TB_TIPOPRODUTO BEFORE INSERT
AS
BEGIN
    new.CODIGO = GEN_ID(GEN_TIPOPRODUTO, 1);
END

-- TABELA TB_PRODUTO -------------------------------
CREATE TABLE TB_PESSOA (
  CODIGO INTEGER NOT NULL,
  COD_TIPOPESSOA INTEGER NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  RG VARCHAR(20),  
  CPF VARCHAR(12),
  CNPJ VARCHAR(25),
  DT_NASC VARCHAR(12),
  EMAIL VARCHAR(100),
  FONE VARCHAR(20),
  CEP VARCHAR(9) NOT NULL,
  LOGRADOURO VARCHAR(100) NOT NULL,
  NUMERO INTEGER,
  BAIRRO VARCHAR(80) NOT NULL,
  CIDADE VARCHAR(80) NOT NULL,
  ESTADO VARCHAR(80) NOT NULL,
  PAIS VARCHAR(50),  
  COMPLEMENTO VARCHAR(100),
  PRIMARY KEY(CODIGO)  
)

ALTER TABLE TB_PESSOA  ADD PRIMARY KEY(CODIGO);
ALTER TABLE TB_PESSOA ADD FOREIGN KEY(COD_TIPOPESSOA) REFERENCES TB_TIPOPESSOA (CODIGO);

CREATE GENERATOR GEN_PESSOA;
SET GENERATOR GEN_PESSOA TO 0;

CREATE TRIGGER TR_PESSOA FOR TB_PESSOA BEFORE INSERT
AS
BEGIN
    new.CODIGO = GEN_ID(GEN_PESSOA, 1);
END



