-- Inclusão
CREATE OR ALTER PROCEDURE SP_ROTA_INSERT ( 
 P_COD_ENTREGADOR INTEGER,
 P_NUM_ROTA INTEGER,
 P_NUM_PEDIDO INTEGER,
 P_STATUS VARCHAR(40)
)
AS 
BEGIN
    INSERT INTO TB_ROTAS (COD_ENTREGADOR,NUM_ROTA,NUM_PEDIDO,STATUS)
      VALUES (:P_COD_ENTREGADOR,:P_NUM_ROTA,:P_NUM_PEDIDO,:P_STATUS);
	  
    UPDATE TB_PEDIDO SET STATUS_PEDIDO = 'PREPARADO' WHERE NUM_PEDIDO =:P_NUM_PEDIDO;	  
 	     
END


