-- STORED PROCEDURE (INCLUSÃO / ALTERAÇÃO / DELEÇÃO) -- TABELA PESSOA 

-- Consulta todos da tabela TB_PESSOA
CREATE OR ALTER PROCEDURE SP_PESSOA_SELECT
RETURNS(
   rCODIGO INTEGER,
   rTIPOPESSOA VARCHAR(50),
   rNOME VARCHAR(100),
   rRG VARCHAR(20),
   rCPF VARCHAR(12),
   rCNPJ VARCHAR(25),
   rDT_NASC VARCHAR(12),
   rEMAIL VARCHAR(100),
   rFONE VARCHAR(20),
   rCEP VARCHAR(9),
   rLOGRADOURO VARCHAR(100),
   rNUMERO INTEGER,
   rBAIRRO VARCHAR(80),
   rCIDADE VARCHAR(80),
   rESTADO VARCHAR(80),
   rPAIS VARCHAR(50),
   rCOMPLEMENTO VARCHAR(100)
)
AS   
BEGIN	
   FOR SELECT P.CODIGO,TP.DESCRICAO,P.NOME,P.RG,P.CPF,P.CNPJ,P.DT_NASC,P.EMAIL,P.FONE,P.CEP,P.LOGRADOURO,P.NUMERO,P.BAIRRO,
              P.CIDADE,P.ESTADO,P.PAIS,P.COMPLEMENTO 
       FROM TB_PESSOA P, TB_TIPOPESSOA TP
       WHERE P.COD_TIPOPESSOA = TP.CODIGO              
   INTO :rCODIGO,:rTIPOPESSOA,:rNOME,:rRG,:rCPF,:rCNPJ,:rDT_NASC,:rEMAIL,:rFONE,:rCEP,:rLOGRADOURO,:rNUMERO,:rBAIRRO,
        :rCIDADE,:rESTADO,:rPAIS,:rCOMPLEMENTO DO
        
   SUSPEND;
END

-- Inclusão
CREATE OR ALTER PROCEDURE SP_PESSOA_INSERT (
 P_COD_TIPOPESSOA INTEGER,
 P_NOME VARCHAR(100),
 P_RG VARCHAR(20),
 P_CPF VARCHAR(12),
 P_CNPJ VARCHAR(25),
 P_DT_NASC VARCHAR(12),
 P_EMAIL VARCHAR(100),
 P_FONE VARCHAR(20),
 P_CEP VARCHAR(9),
 P_LOGRADOURO VARCHAR(100),
 P_NUMERO INTEGER,
 P_BAIRRO VARCHAR(80),
 P_CIDADE VARCHAR(80),
 P_ESTADO VARCHAR(80),
 P_PAIS VARCHAR(50),
 P_COMPLEMENTO VARCHAR(100)
)
AS 
BEGIN
    INSERT INTO TB_PESSOA (COD_TIPOPESSOA,NOME,RG,CPF,CNPJ,DT_NASC,EMAIL,FONE,CEP,LOGRADOURO,NUMERO,BAIRRO,CIDADE,ESTADO,PAIS,COMPLEMENTO)
      VALUES (:P_COD_TIPOPESSOA,:P_NOME,:P_RG,:P_CPF,:P_CNPJ,:P_DT_NASC,:P_EMAIL,:P_FONE,:P_CEP,:P_LOGRADOURO,:P_NUMERO,:P_BAIRRO,:P_CIDADE,:P_ESTADO,:P_PAIS,:P_COMPLEMENTO);
 	     
END

-- Deleção
CREATE OR ALTER PROCEDURE SP_PESSOA_DELETE (P_ID INTEGER)
AS
DECLARE VARIABLE V_COUNT INTEGER;
   
BEGIN
	
	  SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PESSOA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	  
	  IF (V_COUNT > 0) THEN 
	     DELETE FROM TB_PESSOA 
	        WHERE CODIGO = :P_ID;
	  ELSE 
	       EXCEPTION EXC_REGISTRO_INEXISTENTE; 

END

-- Alteração
CREATE OR ALTER PROCEDURE SP_PESSOA_UPDATE (
 P_ID INTEGER, 
 P_COD_TIPOPESSOA INTEGER,
 P_NOME VARCHAR(100),
 P_RG VARCHAR(20),
 P_CPF VARCHAR(12),
 P_CNPJ VARCHAR(25),
 P_DT_NASC VARCHAR(12),
 P_EMAIL VARCHAR(100),
 P_FONE VARCHAR(20),
 P_CEP VARCHAR(9),
 P_LOGRADOURO VARCHAR(100),
 P_NUMERO INTEGER,
 P_BAIRRO VARCHAR(80),
 P_CIDADE VARCHAR(80),
 P_ESTADO VARCHAR(80),
 P_PAIS VARCHAR(50),
 P_COMPLEMENTO VARCHAR(100)
)
AS
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PESSOA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT; 
	 
	  IF (V_COUNT > 0) THEN  
	      UPDATE TB_PESSOA 
	          SET COD_TIPOPESSOA =:P_COD_TIPOPESSOA,
 				            NOME =:P_NOME,
 				              RG =:P_RG,
 				             CPF =:P_CPF,
 				  			CNPJ =:P_CNPJ,
 				  	     DT_NASC =:P_DT_NASC,
 				           EMAIL =:P_EMAIL,
 				  			FONE =:P_FONE,
 				  			 CEP =:P_CEP,
 				      LOGRADOURO =:P_LOGRADOURO,
 				  		  NUMERO =:P_NUMERO,
 				  		  BAIRRO =:P_BAIRRO,
 				 		  CIDADE =:P_CIDADE,
 				  		  ESTADO =:P_ESTADO,
 				  		    PAIS =:P_PAIS,
                  	 COMPLEMENTO =:P_COMPLEMENTO
	        WHERE CODIGO =:P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;

END