-- STORED PROCEDURE (INCLUSÃO / ALTERAÇÃO) -- TABELA PEDIDO

-- Inclusão
CREATE OR ALTER PROCEDURE SP_PEDIDO_INSERT (
 P_COD_CLIENTE INTEGER,
 P_COD_PRODUTO INTEGER,
 P_NUM_PEDIDO INTEGER,
 P_QTD INTEGER,
 P_OBS VARCHAR(100),
 P_CEP VARCHAR(9),
 P_LOGRADOURO VARCHAR(100),
 P_NUMERO INTEGER,
 P_BAIRRO VARCHAR(80),
 P_CIDADE VARCHAR(80),
 P_ESTADO VARCHAR(80),
 P_PAIS VARCHAR(50)
)
AS
BEGIN

    INSERT INTO TB_PEDIDO (COD_CLIENTE,COD_PRODUTO,NUM_PEDIDO,QTD,OBS,CEP,LOGRADOURO,NUMERO,BAIRRO,CIDADE,ESTADO,PAIS)
      VALUES (:P_COD_CLIENTE,:P_COD_PRODUTO,:P_NUM_PEDIDO,:P_QTD,:P_OBS,:P_CEP,:P_LOGRADOURO,:P_NUMERO,:P_BAIRRO,:P_CIDADE,:P_ESTADO,:P_PAIS);
 	     
END

-- Gera o numero de pedidos
CREATE OR ALTER PROCEDURE SP_GERA_NUM_PEDIDO()
RETURNS(
   rNUM_PEDIDO INTEGER
)
AS   
DECLARE VARIABLE vNUMERO INTEGER;
BEGIN	
   FOR select max(tp.NUM_PEDIDO) from TB_PEDIDO tp
   into :vNUMERO DO 
  
   rNUM_PEDIDO = vNUMERO+1;
  
   SUSPEND;
   
END

-- Consulta Pedido
CREATE OR ALTER PROCEDURE SP_PEDIDO_SELECT(
  pNUM_PEDIDO integer
)
RETURNS(
   rNUM_PEDIDO integer,
   rCOD_CLIENTE integer,
   rCEP varchar(12),
   rLOGRADOURO varchar(80),
   rNUMERO integer,
   rBAIRRO varchar(80),
   rCIDADE varchar(80),
   rPAIS varchar(50),
   rCOD_PRODUTO integer,
   rNUM_REF varchar(10),
   rDESCRICAO varchar(60),
   rQTD integer   
)
AS   
BEGIN	
   FOR select 
         tp.NUM_PEDIDO,
         tp.COD_CLIENTE,
         tp.CEP,
         tp.LOGRADOURO,
         tp.NUMERO,
         tp.BAIRRO,
         tp.CIDADE,
         tp.PAIS,
         tb.CODIGO as COD_PRODUTO,
         tb.NUM_REF,
         tb.DESCRICAO,
         tp.QTD 
        from tb_pedido tp, tb_produto tb
        where tp.COD_PRODUTO = tb.CODIGO 
        and tp.NUM_PEDIDO = :pNUM_PEDIDO into :rNUM_PEDIDO,:rCOD_CLIENTE,:rCEP,:rLOGRADOURO,:rNUMERO,
                                              :rBAIRRO,:rCIDADE,:rPAIS,:rCOD_PRODUTO,:rNUM_REF,:rDESCRICAO,:rQTD DO 
  
   SUSPEND;   
END

-- Deleção
CREATE OR ALTER PROCEDURE SP_PEDIDO_DELETE (
   P_NUM_PEDIDO INTEGER
)
AS
DECLARE VARIABLE V_COUNT INTEGER;   
BEGIN
	
	  SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PEDIDO
	   WHERE NUM_PEDIDO = :P_NUM_PEDIDO
	  INTO :V_COUNT;
	  
	  IF (V_COUNT > 0) THEN 
	     DELETE FROM TB_PEDIDO 
	        WHERE NUM_PEDIDO = :P_NUM_PEDIDO;
	  ELSE 
	       EXCEPTION EXC_REGISTRO_INEXISTENTE; 

END


