-- STORED PROCEDURE (INCLUSÃO / ALTERAÇÃO / DELEÇÃO) -- TABELA PRODUTO 

-- Inclusão
CREATE OR ALTER PROCEDURE SP_PRODUTO_INSERT (
 P_COD_TIPOPRODUTO INTEGER,
 P_DESCRICAO VARCHAR(100),
 P_NUM_REF VARCHAR(10),
 P_QUANT INTEGER,
 P_DT_VALIDADE VARCHAR(14),
 P_PRECO_UNIT FLOAT,
 P_TIPOCOMUM BOOLEAN,
 P_TIPOCONTROLADO BOOLEAN,
 P_TIPOSENSIVEL BOOLEAN, 
 P_PRESC_MEDICA VARCHAR(100),
 P_CUIDADO_ARMAZ VARCHAR(100) 
)
AS
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN

	  SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PRODUTO
	   WHERE NUM_REF = :P_NUM_REF
	  INTO :V_COUNT;
	  
	  IF (V_COUNT = 0) THEN 
	      INSERT INTO TB_PRODUTO (COD_TIPOPRODUTO,DESCRICAO,NUM_REF,QUANT,DT_VALIDADE,PRECO_UNIT,TIPO_COMUM,TIPO_CONTROLADO,TIPO_SENSIVEL,PRESC_MEDICA,CUIDADO_ARMAZ)
            VALUES (:P_COD_TIPOPRODUTO,:P_DESCRICAO,:P_NUM_REF,:P_QUANT,:P_DT_VALIDADE,:P_PRECO_UNIT,:P_TIPOCOMUM,:P_TIPOCONTROLADO,:P_TIPOSENSIVEL,:P_PRESC_MEDICA,:P_CUIDADO_ARMAZ);
	  ELSE 
	       EXCEPTION EXC_REGISTRO_INEXISTENTE; 
 	     
END


--Alteração
CREATE OR ALTER PROCEDURE SP_PRODUTO_UPDATE (
 P_ID INTEGER,
 P_COD_TIPOPRODUTO INTEGER,
 P_DESCRICAO VARCHAR(100),
 P_NUM_REF VARCHAR(10),
 P_QUANT INTEGER,
 P_DT_VALIDADE VARCHAR(14),
 P_PRECO_UNIT FLOAT,
 P_TIPOCOMUM BOOLEAN,
 P_TIPOCONTROLADO BOOLEAN,
 P_TIPOSENSIVEL BOOLEAN, 
 P_PRESC_MEDICA VARCHAR(100),
 P_CUIDADO_ARMAZ VARCHAR(100)
)
AS
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PRODUTO
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT; 
	 
	  IF (V_COUNT > 0) THEN  
	      UPDATE TB_PRODUTO 
	          SET COD_TIPOPRODUTO =:P_COD_TIPOPRODUTO,
 				        DESCRICAO =:P_DESCRICAO,
 				          NUM_REF =:P_NUM_REF,
 				            QUANT =:P_QUANT,
 				  	  DT_VALIDADE =:P_DT_VALIDADE,
 				  	   PRECO_UNIT =:P_PRECO_UNIT,
 				       TIPO_COMUM =:P_TIPOCOMUM,
 				  TIPO_CONTROLADO =:P_TIPOCONTROLADO,
 				    TIPO_SENSIVEL =:P_TIPOSENSIVEL,
 				     PRESC_MEDICA =:P_PRESC_MEDICA,
 				    CUIDADO_ARMAZ =:P_CUIDADO_ARMAZ
 		        WHERE CODIGO =:P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;

END


-- Deleção de Produto
CREATE OR ALTER PROCEDURE SP_PRODUTO_DELETE (P_ID INTEGER)
AS
DECLARE VARIABLE V_COUNT INTEGER;
   
BEGIN
	
	  SELECT COALESCE(COUNT(*), 0)
	   FROM TB_PRODUTO
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	  
	  IF (V_COUNT > 0) THEN 
	     DELETE FROM TB_PRODUTO 
	        WHERE CODIGO = :P_ID;
	  ELSE 
	       EXCEPTION EXC_REGISTRO_INEXISTENTE; 

END